### ISSUE TITLE
Error during user initialisation iteration

### ISSUE THREAD

**Issue by peeohvee** [sgratzl/slack_cleaner2#12]
**Describe the bug**
During tantalisation, SlackCleaner appears to iterate over the user list. The iteration is interrupted and an error is thrown
```
>>> from slack_cleaner2 import *
>>> s = SlackCleaner('xoxp-xxx')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/slack_cleaner2/model.py", line 706, in __init__
    self.myself = next(u for u in self.users if u.email == profile["email"])
StopIteration
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Copy the two lines of code above.
2. Enter

**Expected behaviour**
Successful initialisation.
 
**Versions**
Python 3.6.9
slack-cleaner 2.0.1

**Additional context**
Granted scopes
```
channels:history
channels:read
channels:write
chat:write
files:read
files:write
groups:history
groups:read
groups:write
im:history
im:read
im:write
links:read
links:write
mpim:history
mpim:read
mpim:write
remote_files:read
remote_files:share
remote_files:write
search:read
users.profile:read
users:read
users:read.email
```

**Comment by sgratzl** [comment]
interesting, seems like it couldn't find itself = the user that provided the token
