### ISSUE TITLE
Improve cronjob compatibility: less and more private logging to console

### ISSUE THREAD

**Issue by puzzlement** [sgratzl/slack_cleaner2#22]
**Is your feature request related to a problem? Please describe.**

slack_cleaner2 is very verbose on stdout both via always sending DEBUG logs to the console and via occasional direct calls to `sys.stdout`. This means a few things for cronjobs:

1. it will dump a lot of content into logs/emails whenever it is run including progress `.` characters and other non-error material
2. some of this will be sensitive information, including data and metadata from messages, eg:

```
xcannot delete entry: nickname:timestamp (nickname (channel_id) Real Name): excerpt of actual message: cant_delete_message
```

This amounts to permanent retention of any message there's ever an error deleting, unless one scrubs one's email or cron errors very carefully.

**Describe the solution you'd like**

More control over logging level, including to console, and including suppression of metadata and message contents.

**Comment by sgratzl** [comment]
what about a `quiet` option that will avoid writing directly to stdout. regarding the logging, a simpler way to configure the log level could help

**Comment by sgratzl** [comment]
in the next version there will be two new options
 * provide a custom `logging.Logger` instance -> thus you can customize what level is how logged
 * set `show_progress=False` to disable the progress dump (. or x)

**Comment by puzzlement** [comment]
Those options are good, but it's not clear to me that this will still report errors I need to know about (may depend on what you log at which log level).

Want to know (at least potentially): message could not be deleted.

Do not necessarily want logged, at least not at the same level: contents of message that could not be deleted.

**Comment by sgratzl** [comment]
this one should log just the critical message and one can handle the error upon deletion oneself:

```py
logger = logging.getLogger('slack-cleaner')
logger.setLevel(logging.ERROR)
s = SlackCleaner(token, logger=logger, show_progress=False)

for msg in s.msgs():
  error = msg.delete()
  if error:
    print('error')
  else:
    print('ok')
```
