### ISSUE TITLE
How to check for author of message?

### ISSUE THREAD

**Issue by dave7895** [sgratzl/slack_cleaner2#23]
I am stuck trying to check if the author is a certain user before deleting. Could anybody help me?

**Comment by sgratzl** [comment]
can you a bit more precise where you are stuck when following https://github.com/sgratzl/slack_cleaner2#token

**Comment by sgratzl** [comment]
> I am stuck trying to check if the author is a certain user before deleting. Could anybody help me?

each `SlackMessage` object has a `.user` property (https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.model.SlackMessage.user) which contains the user that wrote the message.

**Comment by dave7895** [comment]
I managed to find the token. Had just overlooked it.

**Comment by dave7895** [comment]
I know that there is a `.user` property but I did not manage to find the right "thing" to compare it to. Wanted to delete messages in IMs but could not check for the author before deleting to avoid warnings that the message could not be deleted.

**Comment by sgratzl** [comment]
since you can only delete IM message triggered by the user generating the token you can do the following:

```py
for msg in s.msgs(s.ims):
  if msg.user == s.myself:
    msg.delete()
```

**Comment by dave7895** [comment]
Oh ok. thank you. Additionally I could find an option to paginate to go through more than 1000 messages. Hope I do not bother you.

**Comment by sgratzl** [comment]
> Additionally I could find an option to paginate to go through more than 1000 messages.

what do you mean? it should automatically iterate over all messages (within the 10k limit of course)

https://github.com/sgratzl/slack_cleaner2/blob/master/slack_cleaner2/model.py#L218

**Comment by dave7895** [comment]
Ok. maybe I did something wrong. Tried to delete all of my messages and had a counter running for total and deleted and total was constantly 1000 and deleted got about halved every iteration.
