### ISSUE TITLE
Invalid syntax error

### ISSUE THREAD

**Issue by bjmrey** [sgratzl/slack_cleaner2#25]
**Describe the bug**
I am getting the following error when trying to import slack cleaner from the python console:

    Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39)
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
     >>> from slack_cleaner2 import *
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/benjaminrey31/Library/Python/2.7/lib/python/site
    packages/slack_cleaner2/__init__.py", line 5, in <module>
        from .predicates import and_, or_, is_not_pinned, is_bot, match, is_name, match_text, 
    match_user, is_member, by_user, by_users
      File "/Users/benjaminrey31/Library/Python/2.7/lib/python/site 
    packages/slack_cleaner2/predicates.py", line 20
        def __init__(self, children: Optional[List[PreciateFun]] = None):**
                                   ^
    SyntaxError: invalid syntax

**To Reproduce**
I have installed slack-cleaner using the following command to avoid ssl and permission errors:
`python -m pip install --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org slack-cleaner2 --user`

**Expected behavior**
I should not have an error, I guess!

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.4

**Comment by sgratzl** [comment]
python 2.7 is not longer supported since also its official support time has ended. 

The code uses MyPy typings to ensure code security requiring Python 3.6 at minimum.

**Comment by bjmrey** [comment]
Ok, thanks!
