### ISSUE TITLE
conversations.replies: unknown error occurred: thread_not_found

### ISSUE THREAD

**Issue by jpwynn** [sgratzl/slack_cleaner2#29]
Execution continues OK, but seems like whenever I invoke `msg.delete(replies=True, files=True)` when it hits a thread, it prints a "." when as iterates/deletes each message in the thread but then it prints a "conversations.replies: unknown error occurred: thread_not_found" message when it finishes the thread:

```
........conversations.replies: unknown error occurred: thread_not_found
```

Doesn't hurt anything, execution continues.

But I wonder if perhaps the logic to delete a message that is a a thread deletes the "parent of thread" message first (which actually leaves a empty message that says "this message is deleted" that is the parent of the thread, then iterates through each child, then generates the "thread not found" error message when re-deleting then now-empty parent. Just a guess.

**Comment by sgratzl** [comment]
Do you also iterate over the messages with `msgs(replies=True)`? If so it explains the behavior, since you try to try to delete the same thread twice then.
