### ISSUE TITLE
Delete direct messages (DMs) and automatic messages sent by apps

### ISSUE THREAD

**Issue by Freelensia** [sgratzl/slack_cleaner2#32]
@sgratzl could you share some sample scripts to delete messages:

1. between slack username peter and username john as DM
2. sent from the app Asana (or Google Drive or any other app) to slack username john as DM (not in a channel)

And a question, can your script delete DMs between any 2 users in the slack workspace? With the old slack cleaner we had to use a token of one of the user in the conversation.

**Comment by sgratzl** [comment]
this version of the slack cleaner has the same restrictions as the other one, since they are both built upon the official slack api.

The slack API only allows to delete direct messages that were written by the token owner

**Comment by Freelensia** [comment]
> The slack API only allows to delete direct messages that were written by the token owner

Hmm I think this is not true. I just deleted all messages in a room and it has many messages written by other people.
In any case, could you share some sample scripts? @sgratzl

**Comment by sgratzl** [comment]
> The slack API only allows to delete direct messages that were written by the token owner

I was referring to DM messages. the restrictions doesn't apply for private/public channels.

**Comment by sgratzl** [comment]
assuming that the Slack token is issued for username john - otherwise you cannot access his DM. 

untested code:

```py
from slack_cleaner2 import *
s = SlackCleaner('SECRET TOKEN')
```

> * between slack username peter and username john as DM

```py
channel_with_john = next(c for c in s.ims if c.user.name == 'john', None)
```

see also:
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.SlackCleaner.ims
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.model.SlackDirectMessage
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.model.SlackUser

> 
> * sent from the app Asana (or Google Drive or any other app) to slack username john as DM (not in a channel)

```py
channels_with_an_app = [c for c in s.ims if c.user.bot]
```

see also:
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.SlackCleaner.ims
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.model.SlackDirectMessage
 * https://slack-cleaner2.readthedocs.io/en/latest/api.html#slack_cleaner2.model.SlackUser

**Comment by Freelensia** [comment]
> ```python
> channel_with_john = next(c for c in s.ims if c.user.name == 'john', None)
> ```

Hi @sgratzl just to clarify, the text "john" in this code is referring to the other person, not me right? 
Is it possible to loop through all users and delete all DMs that I have with them?

**Comment by sgratzl** [comment]
`s.ims` return a list of direct message channels the token owner has. The other person of the DM channel is available using `c.user.name`. 

and yes, `john` was in this case the other person. you can access yourself using `s.myself`

**Comment by Freelensia** [comment]
Thanks @sgratzl so your script lists the msg only, or actually deletes them?
And how to loop thru all DMs between myself and all users and delete all msg?
Previously you showed me how to delete msg in any channel:
'for msg in s.c['bot-bitbucket'].msgs(with_replies=True): msg.delete()'

**Comment by Freelensia** [comment]
> Thanks @sgratzl so your script lists the msg only, or actually deletes them?
> And how to loop thru all DMs between myself and all users and delete all msg?
> Previously you showed me how to delete msg in any channel:
> `for msg in s.c['bot-bitbucket'].msgs(with_replies=True): msg.delete()`

@sgratzl sorry to bother you again, did u have time to check this?
