### ISSUE TITLE
How to delete message from private message.

### ISSUE THREAD

**Issue by goffity** [sgratzl/slack_cleaner2#35]
How to delete messages from private messages.

I try to delete with python code.
```
import time
from slack_cleaner2 import *

s = SlackCleaner("${token}",1)

f = is_not_pinned()
before = a_while_ago(months=2)

for c in s.ims:
  with s.log.group(c.name):
    for msg in filter(f,c.msgs(before=before)):
      msg.delete(as_user=True)
s.log.summary() 
```

It always displays error "cant_delete_message", but if I try to delete in group or channel it works fine.
What I messing in this code.

- Version: 2.4.2
- Python Version: 3.7.4

**Comment by sgratzl** [comment]
see note in README: https://github.com/sgratzl/slack_cleaner2#deleting-messages-from-11-ims

the slack api doesn't allow to delete direct messages that are not written by you.

**Comment by goffity** [comment]
Ohh! Thanks, @sgratzl. I know what I miss now.
I have more questions. If I cannot use slack_cleaner to delete 1:1 message, Is there any other way to do it?

**Comment by sgratzl** [comment]
you can only delete the messages that the token owner wrote. This is a limitation of the slack rest api not of this tool using it.

**Comment by goffity** [comment]
OK, Thanks @sgratzl
