### ISSUE TITLE
Option to bulk delete user

### ISSUE THREAD

**Issue by cinghaman** [sgratzl/slack_cleaner2#37]
Is there a way to modify the python code to add an option to be able to bulk delete users, from email list which will compare users email in slack or setting up some other criteria?

**Comment by sgratzl** [comment]
what do you mean? in this library you have to decide and iterate over the messages yourself. The library provides you just with a model around the slack api for doing that more easily, see also https://slack-cleaner2.readthedocs.io/ for its api docs

**Comment by cinghaman** [comment]
> what do you mean? in this library you have to decide and iterate over the messages yourself. The library provides you just with a model around the slack api for doing that more easily, see also https://slack-cleaner2.readthedocs.io/ for its api docs

At the moment all the option show for deleting messages, i was wondering if there is a way to delete/kick out users from channels on bulk.

**Comment by sgratzl** [comment]
atm. the library has the focus on deleting messages but not managing slack. you might wanna take a look at https://github.com/slackapi/python-slackclient
