### ISSUE TITLE
Not handling tombstoned files (hidden_by_limit) file responses correctly

### ISSUE THREAD

**Issue by raycardillo** [sgratzl/slack_cleaner2#42]
We use the cleaner for our family account that has been running for several years. I don't know if it's a new Slack API feature, but some file entries appear to be coming back with `hidden_by_limit` and the rest of the content is redacted. See their spec here:

https://api.slack.com/methods/files.revokePublicURL#response

- Version: 3.0.1
- Python Version: 3.8

I discovered this while trying to run the script for our account again and we must now have "tombstone" files. I'll workaround this locally for myself, but wanted to report this to you so a proper fix can be made as well. To debug, I printed the response entry and that's how I discovered the `hidden_bt_limit` response.

Here was the error I was receiving (which was cryptic and not really the root cause):
```
Traceback (most recent call last):
  File "clean_general_before2019.py", line 5, in <module>
    for msg in s.c.general.msgs(before="20191201", with_replies=True):
  File "/home/ray/.local/lib/python3.8/site-packages/slack_cleaner2/model.py", line 232, in msgs
    s_msg = SlackMessage(msg, user, self, self._slack)
  File "/home/ray/.local/lib/python3.8/site-packages/slack_cleaner2/model.py", line 386, in __init__
    self.files = [SlackFile(f, user if user else slack.resolve_user(
  File "/home/ray/.local/lib/python3.8/site-packages/slack_cleaner2/model.py", line 386, in <listcomp>
    self.files = [SlackFile(f, user if user else slack.resolve_user(
  File "/home/ray/.local/lib/python3.8/site-packages/slack_cleaner2/model.py", line 518, in __init__
    self.name = entry["name"]
```

So I put in a print statement for the entry at line 518 and discovered it was:
```
{'id': 'XX55X5XX5', 'mode': 'hidden_by_limit'}
```

So of course the line that attempts to perform `self.name = entry["name"]` will fail because the entry response does not contain a `name` key.

Apparently this is related to their somewhat recent implementation for "tombstoned files" and there is a way to delete them as well... which I will see if I can get working quickly... but I don't work in Python all that often so I would rather have you review and consider a proper approach given this new information. ;)

For information about "tombstoned files" see:
https://api.slack.com/changelog/2019-03-wild-west-for-files-no-more

p.s., Thanks for the great work on this project!

**Comment by sgratzl** [comment]
thx fixed with v3.0.2
