### ISSUE TITLE
[ERROR] Failed to fetch members for the channel.

### ISSUE THREAD

**Issue by bmerino** [sgratzl/slack_cleaner2#44]
I typically run slack cleaner daily at work to remove messages for security's sake. This is done purely for direct messages and I've had 0 issues since I first put this together when slack cleaner 2 came out. 

For some reason, starting yesterday, I'm now receiving the below error and simply receive the "cannot delete entry:..." message for all messages. Prior, you would only see this message for messages that weren't your own (since I'm deleting in 1v1 DMs). The error itself shows only at the beginning. 

Also, I went ahead and reset the OAuth permissions and reinstalled the app in the workspace, but that had no effect. 

**Error Message:**

<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x0381D540>: unknown error occurred: The request to the Slack API failed.

The server responded with: {'ok': False, 'error': 'fetch_members_failed', 'response_metadata': {'messages': ['[ERROR] Failed to fetch members for the channel.']}}

**Screenshots**

![image](https://user-images.githubusercontent.com/43735807/106774195-b94b1d80-65f6-11eb-811a-e0b2653fa198.png)

**Comment by sgratzl** [comment]
which version are you using?

**Comment by bmerino** [comment]
Sorry about that, I should have added above:

 __version__ = "3.0.2"

**Comment by sgratzl** [comment]
hm....

two questions I haven't have an answer yet:
 1. I don't know what has changed in the api such that this error occurs
 2. this part of the code should have actually caught that exception and handle it with a warning since the members are not essential; 
 
https://github.com/sgratzl/slack_cleaner2/blob/85c38783266acd8efffe167f6317c5526c00b9a0/slack_cleaner2/model.py#L847-L857

**Comment by sgratzl** [comment]
as indicated in #40, slack lists now archived channels and for archived channels one is not able to fetch members. 

can you try out: https://github.com/sgratzl/slack_cleaner2/releases/tag/v3.0.3

**Comment by sgratzl** [comment]
closing since #40 reported that the bug has been fixed
