### ISSUE TITLE
Deprecated methods

### ISSUE THREAD

**Issue by ag-tcm** [sgratzl/slack_cleaner2#46]
The fated Slack API change is upon us.

When instantiating SlackCleaner object, getting error:
slacker.Error: method_deprecated from slack_cleaner2.py, line 96.

See: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

Think slack_cleaner2 is salvageable?

**Comment by sgratzl** [comment]
which version are you using?

does it say which method was deprecated?

**Comment by ag-tcm** [comment]
Using 1.0.2

https://api.slack.com/methods/channels.list is the culprit.

**Comment by sgratzl** [comment]
the latest version is slack-cleaner2: v3.0.3, please update and try again

**Comment by ag-tcm** [comment]
Very strange, I installed it with "pip install slack_cleaner2" a few hours
ago. Perhaps I installed it years ago and forgot the "-U". Updated now.
Sorry for the false alarm :-)

**Comment by danarteaga** [comment]
Had the same issue today - the above command did the trick
