### ISSUE TITLE
"after" keyword not working for "files" function.

### ISSUE THREAD

**Issue by ag-tcm** [sgratzl/slack_cleaner2#47]
After my false alarm yesterday I'm hesitant to post this since there is a high probability it is operator error but here goes:

I'm trying to delete all files in a channel after some date.

```
s.c['slackbot'].files(after=20210225):
   print(f'Deleting: {f} {f.delete()}')
```
I see that files are being deleted but they are all files from a long time ago.
Have I formatted the argument for "after" correctly? I based it on [https://github.com/sgratzl/slack-cleaner/issues/79#issuecomment-625239340](https://github.com/sgratzl/slack-cleaner/issues/79#issuecomment-625239340)

**Comment by sgratzl** [comment]
can you try out the just published version v3.0.4, please

**Comment by ag-tcm** [comment]
Upgraded to 3.0.4.

To test this I sent a file to slackbot and then tried NOT to delete it by putting after=2021027...but it still deleted the file.

**Comment by sgratzl** [comment]
I was checking the code, if you provide a number it is interpreted as an timestamp. 

So, can you try to wrap it into a string which will be parsed as a time

```python
s.c['slackbot'].files(after='20210225'):
   print(f'Deleting: {f} {f.delete()}')
```

see also https://github.com/sgratzl/slack_cleaner2/blob/e650dc45f0fd08b7c1c1c4cdc7de6aa083b3888c/slack_cleaner2/model.py#L689-L699

**Comment by ag-tcm** [comment]
That makes sense, thank you.
