### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by datadodo** [sgratzl/slack_cleaner2#53]
HI ,
When trying to print or delete messages from a private channel i am met with the following error :
AttributeError: 'NoneType' object has no attribute 'name'

Steps to reproduce:

for channel in s.conversations:
    for msg in channel.msgs(with_replies=True):
        if msg.user.name == 'femi.situ-amoo' and not msg.pinned_to:
            print(msg)

terminal output is :

general:1608025326.0081 (femi.situ-amoo (U01GVRYE403) femi amoo): <@U01GVRYE403> has j
random:1608025326.007 (femi.situ-amoo (U01GVRYE403) femi amoo): <@U01GVRYE403> has j
Traceback (most recent call last):
  File "/Users/Femi/Documents/slack/Slackupdated/slack_cleaner2-main/deletespecicuser.py", line 8, in <module>
    if msg.user.name == 'femi.situ-amoo' and not msg.pinned_to:
AttributeError: 'NoneType' object has no attribute 'name'

Process finished with exit code 1

I am an owner in my workspace and have given all the listed permissions. 

![image](https://user-images.githubusercontent.com/4274893/117834297-f31f6600-b26e-11eb-83c6-b4a332dbe0f4.png)

**Comment by sgratzl** [comment]
could it be that this message is a bot message and thus doesn't have a user?

**Comment by datadodo** [comment]
im itterating over all messages and only printing messages that are from my user, there are bots in the general chat and the random chat and it was able to parse okay there.

**Comment by sgratzl** [comment]
my point is that `msg.user` can be None if the author cannot be resolved, e.g., when the message was written by a bot

https://github.com/sgratzl/slack_cleaner2/blob/53be19c597425271bd5e67a2bf844e0c0cef2d9c/slack_cleaner2/model.py#L338-L341

```python
 if (msg.user and msg.user.name == 'femi.situ-amoo') and not msg.pinned_to:
```
should work

**Comment by datadodo** [comment]
Amazing !  Thank you, that did work,  im attempting to delete every message from a specific user, is there a better way to do this than my attempt above ? as im now hitting the rate limit. 


the new error:
(conversations.replies: unknown error occurred: The request to the Slack API failed.
The server responded with: {'ok': False, 'error': 'ratelimited'})

(im thinking of introducing a count to the messages found to 19 and when this is reached reset the count and wait 1 min to solve this )

**Comment by sgratzl** [comment]
I didn't know that there is also a rate limit on the replies call. The delete call should automatically handle it, see https://github.com/sgratzl/slack_cleaner2/blob/53be19c597425271bd5e67a2bf844e0c0cef2d9c/slack_cleaner2/model.py#L410-L418

I will create a new issue for it
