### ISSUE TITLE
Initialization Delay

### ISSUE THREAD

**Issue by aeron7** [sgratzl/slack_cleaner2#55]
Well, it takes quite decades to load when the Slack Community has more members. In fact, I was trying on a community with 10K members. It died for 5 mins and became alive after some time.

Often it ends in `urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>`

Then, After 2-3 trials, it works. So I had to While True and try, except this.

Is there any way to reduce this time gap. Like what is the necessity of downloading all the channel names, user names to local variables when we can check the conditions on the fly.

**Comment by sgratzl** [comment]
In such cases I would  directly use the SlackAPI (https://slack.dev/python-slack-sdk/). It it will you the most flexibility in doing what you want. slack_cleaner2 provides a wrapper around it to be more convenient for basic operations and for that it loads all the meta data first.
