### ISSUE TITLE
Just Delete FIles?

### ISSUE THREAD

**Issue by tkintenn** [sgratzl/slack_cleaner2#56]
It seems this is deleting messages AND files?

We just need to delete the files (images mainly). Is that possible with the code provided?`

**Comment by sgratzl** [comment]
There is also the `.files()` (https://github.com/sgratzl/slack_cleaner2/blob/53be19c597425271bd5e67a2bf844e0c0cef2d9c/slack_cleaner2/model.py#L1010)  method  of the SlackCleaner object which lists all the files and then they can be deleted

**Comment by ZuzooVn** [comment]
Can we delete files and all their replies? @sgratzl
