### ISSUE TITLE
KeyError: 'user' when trying to delete files

### ISSUE THREAD

**Issue by jimmyville** [sgratzl/slack_cleaner2#60]
I've been using SlackCleaner2 for a while for purging messages without issue - it's great. However, I'm trying to loop through and purge old files but keep hitting the following error. 

```
Traceback (most recent call last):
  File "/purge-files.py", line 6, in <module>
    for f in s.files(before=a_while_ago(months=12)):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/slack_cleaner2/model.py", line 586, in list
    yield SlackFile(slack_file, slack.resolve_user(slack_file["user"]), slack)
KeyError: 'user'
```

Do you know of a solution or workaround for this issue?

**Comment by sgratzl** [comment]
can you verify that you have all the required scopes?

**Comment by jimmyville** [comment]
I can confirm I've applied all the required permissions. I discovered it was an issue with some older messages (possibly with deleted users) so I purged these ones manually and then applied your script on a timeframe (eg: files in past 36 months).
