### ISSUE TITLE
Script is generating dummy users?

### ISSUE THREAD

**Issue by saschae-kolibri** [sgratzl/slack_cleaner2#62]
Hi there,
I have created a script to delete all messages in a private channel which are older then x days (incl. replies and files).
When running the script it returns multiple returns like this:
`user U014L8MDCJF not found - generating dummy one`
Is this intended? 

In addition the bot is lacking apparently some permissions, but I used the permissions given in the introduction.
```
conversations.list (mpim): missing scope error: mpim:read is missing
conversations.list (im): missing scope error: im:read is missing
conversations.history: missing scope error: channels:history is missing
```

my script for reference:
```
from slack_cleaner2 import *

s = SlackCleaner('xoxp-TOKEN')

# delete all messages in #some_test_channel channel
for msg in filter(match('.some_test_channel'), s.msgs(before=a_while_ago(days=28))):
  # delete messages, its files, and all its replies (thread)
  msg.delete(replies=True, files=True)
```

**Comment by sgratzl** [comment]
> Do you have an explanation for the spam of `user XXXXXXXXXXX not found - generating dummy one` ?

at the beginning slack_cleaner lists all users that are in the slack workspace. However, it can happen that this either didn't work or it still cannot find certain users. One reason might be that the users were deleted but some messages are still around.

**Comment by sgratzl** [comment]
> After creating a few dummy users I'm getting the following error:
> 
> `<function SlackCleaner.safe_paginated_api.<locals>.list_page at 0x7f1b7cd40040>: unknown error occurred: The request to the Slack API failed. (url: https://www.slack.com/api/conversations.members)`

that should have been fixed with the latest release
