### ISSUE TITLE
files(before=...) is capped at 10 entries and results seem to be cached

### ISSUE THREAD

**Issue by mattfeury** [sgratzl/slack_cleaner2#65]
When I run channel.files(before=ts), I expect to get a list/generator of all files before that date in a given channel. However, I'm not seeing that as the case.

**To Reproduce**

I was able to run this code:

```
s = SlackCleaner("TOKEN")
num_deleted = 0
ts = 1635872414 
for channel in filter(lambda channel: channel.name.startswith("channel-prefix-"), s.groups):
  files = channel.files(before=ts)
  for file in files:
    print("deleting " + file.name)
    file.delete()
    num_deleted = num_deleted + 1

```

It successfully deleted ~39 files from about ~4 private channels.

However, I changed the ts to something prior to the previously run date, and STILL found files to delete:

```
ts = 1635509825
for channel in filter(lambda channel: channel.name.startswith("channel-prefix-"), s.groups):
  files = channel.files(before=ts)
  for file in files:
    print("deleting " + file.name)
    file.delete()
    num_deleted = num_deleted + 1
```

It successfully deleted ~40 files from about ~4 private channels, despite the timestamp (1635509825) being before the previously run timestamp (1635872414).

- Version: 3.0.6
- Python Version: Python 3.9.6

Am I misunderstanding how this works or am I doing something wrong? Appreciate the help!

**Comment by mattfeury** [comment]
Note that I am seeing the same functionality with deletes by user as well. Seems to cap at 10 which i'm sure is some slack limit, but i'm also surprised that re-running does not continue deleting the next files in order.

e.g.:

```
from slack_cleaner2 import *
from datetime import datetime, timedelta

s = SlackCleaner("TOKEN")

today = datetime.now()    
n_days_ago = today - timedelta(days=7)
ts = int(round(n_days_ago.timestamp()))

def delete_since(timestamp):
  num_deleted = 0
  files = s.myself.files(before=timestamp)
  for file in files:
    print("deleting " + file.name + " : " + str(file.id))
    file.delete()
    num_deleted = num_deleted + 1
  
  print("deleted " + str(num_deleted) + " files!")
```

if i run:

```
delete_since(ts) # deletes 10 files
delete_since(ts) # deletes 0 files
delete_since(ts - 100) # deletes 10 files
```

**Comment by mattfeury** [comment]
note that if i sleep for 30s, it does seem to continue. so perhaps some caching is at play:

```
delete_since(ts) # deletes 10 files
sleep(30)
delete_since(ts) # deletes 10 files
```

**Comment by sgratzl** [comment]
can you try the latest version, please

**Comment by sgratzl** [comment]
ok, thx I just published https://github.com/sgratzl/slack_cleaner2/releases/tag/v3.1.1 which should fix it

**Comment by mattfeury** [comment]
ah incredible. thanks so much for the quick response and quick fix. it looks to be working great now!
