### ISSUE TITLE
Errors with Docker and versions > v3.1.0

### ISSUE THREAD

**Issue by EarthlingDavey** [sgratzl/slack_cleaner2#66]
When I try to run a script in a docker container, it will fail with an error. See below for trace.

**To Reproduce**

1. Create Dockerfile with contents

```
FROM python:3.7-alpine
LABEL maintainer="Samuel Gratzl <sam@sgratzl.com>"
VOLUME "/backup"
WORKDIR /backup
RUN pip --no-cache-dir install slack-cleaner2
CMD ["python", "-"]
```

2. Create script.py with contents

```
from slack_cleaner2 import *
s = SlackCleaner('SECRET TOKEN')
# list of users
s.users
# list of all kind of channels
s.conversations
```

3. Run `docker build -t slack_cleaner2 .`

4. `cat script.py | docker run -i slack_cleaner2`

5. Result is the error: 
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/__init__.py", line 5, in <module>
    from .predicates import and_, or_, is_not_pinned, is_bot, match, is_name, match_text, match_user, is_member, by_user, by_users
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/predicates.py", line 9, in <module>
    from .model import SlackUser
  File "/usr/local/lib/python3.7/site-packages/slack_cleaner2/model.py", line 12, in <module>
    from functools import cached_property
ImportError: cannot import name 'cached_property' from 'functools' (/usr/local/lib/python3.7/functools.py)
```

**Expected behavior**

The script runs without an error. Expected behavior can be seen if you specify version 3.0.7 or earlier in the Dockerfile.

```
FROM python:3.7-alpine
LABEL maintainer="Samuel Gratzl <sam@sgratzl.com>"
VOLUME "/backup"
WORKDIR /backup
RUN pip --no-cache-dir install slack-cleaner2==3.0.7
CMD ["python", "-"]
```

**Context**

- Version: > v3.1.0
- Python Version: 3.7
- Using Docker

Lastly... Thanks for the awesome script. It will save me a tonne of time 👊🏼✌🏼

**Comment by sgratzl** [comment]
can you try using a Python 3.9 version, 

i.e.
```
FROM python:3.9-alpine
```

**Comment by EarthlingDavey** [comment]
> `FROM python:3.9-alpine`

This works :) Would you like me to update the readme & PR?

**Comment by sgratzl** [comment]
thx I did it already and filed #67 for any further changes
