### ISSUE TITLE
unexpected keyword argument 'team_id' after going to 3.1.1 from 3.0.1

### ISSUE THREAD

**Issue by kriketan** [sgratzl/slack_cleaner2#68]
Using the example code from the readme (I had something a bit more complex, but scaled back to that), I am seeing new behavior with no changes to my app, API key, permissions, etc. on the slack side. Specifically, I get this error on run:

`...slack_cleaner2/model.py", line 1175, in __init__
    client = WebClient(token=token, team_id=team_id)
TypeError: __init__() got an unexpected keyword argument 'team_id'`

This is thrown on `s = SlackCleaner('SECRET TOKEN')`

**Comment by sgratzl** [comment]
can you verify that you installed `slack_sdk` is the latest version available

**Comment by kriketan** [comment]
That's all it was. Up and running now. Thanks!
