### ISSUE TITLE
Usage in private channels where the Slack app creator is not part of

### ISSUE THREAD

**Issue by sMuve** [sgratzl/slack_cleaner2#70]
First of all: Happy new year and  thank you for this package 👍 

I have created the Slack app in our workspace and tested it successfully, which means that it was able to delete messages, conversations and attached files in a given private channel where I'm part of 🙌 

Then I tried to apply this to a private channel where I'm not part of. Therefore a colleague added the app to the private channel and I ran my script, which returned my this error:
```
Traceback (most recent call last):
  File "/.../slack_cleaner2/delete_messages.py", line 7, in <module>
    for msg in s.c['some-channel'].msgs(before=a_while_ago(days=14)):
AttributeError: 'NoneType' object has no attribute 'msgs'
```

Here is my script:
```
from slack_cleaner2 import *

# create an object named SlackCleaner with the given token
s = SlackCleaner('xoxp-...')

# delete all messages (incl. replies and if older than 14 days) in #some-channel channel
for msg in s.c['some-channel'].msgs(before=a_while_ago(days=14)):
    msg.delete(replies=True)

# shows a summary of the actions
s.log.summary()
```

- Versions:
- Python: 3.8
- slack_clenaer2 3.1.1
- colorama 0.4.4
- python_dateutil 2.8.2
- requests 2.26.0
- slack_sdk 3.13.0

Is there no way that this app will work in a private channel, where I'm not part of?

Thanks in advance :-)

**Comment by sgratzl** [comment]
The user token you created is bound by the permissions of your user. Thus, slack cleaner can only access the channels which the user of the user token has access to.
