### ISSUE TITLE
When running against a channel using CLI, slack-cleaner2 isn't deleting replies

### ISSUE THREAD

**Issue by y4utj4** [sgratzl/slack_cleaner2#71]
I ran this utility over my general channel for slack and though it deleted all of the messages, it did not remove any of the replies. I'm not sure if there's a switch I missed when running but there is no switch to remove the replies. 

command run: slack-cleaner2 --token xoxp-<token> --channel "general" --message --user "*" --before 20200109 --as_user --perform

Any guidance would be appreciated, thanks!!!

**Comment by sgratzl** [comment]
the CLI interface of slack-cleaner2 is very rudimentary. The main usage is using it as a library. see also the README or https://github.com/sgratzl/slack-cleaner/discussions/97#discussioncomment-913528 for some migration hints

**Comment by y4utj4** [comment]
Makes total sense. Got it working, thanks for the quick response!!!
