### ISSUE TITLE
Excellent library - tutorial 

### ISSUE THREAD

**Issue by perfecto25** [sgratzl/slack_cleaner2#72]
Hello, thanks for the excellent lib

I added a tutorial on how to set all this up here:

https://perfecto25.medium.com/delete-all-messages-from-a-slack-channel-b61c6e74f69b

**Comment by sgratzl** [comment]
thx. a comment about your code. a simplified version would be:

```
from slack_cleaner2 import SlackCleaner

token = "xoxp-XXXXXXXXX"

s = SlackCleaner(token)

channel = s.c["name-of-your-channel"]

for msg in channel.msgs():
  print(msg)
  # delete messages, its files, and all its replies (thread)
  # msg.delete(replies=True, files=True)
```
