### ISSUE TITLE
Not able to get user information using the bot token

### ISSUE THREAD

**Issue by wonjoonSeol** [sgratzl/slack_cleaner2#74]
Hello, 

it seems like I can't use slack_cleaner2 to remove my own messages in a DM.
I have added the necessary scope mentioned in README and installed an app made from my accont on the workspace 
but this is what I get:

```
s = SlackCleaner("...")

print('users', s.users)   # users [] <- empty
print(s.ims)  # [slackbot] <- only slackbot
print('instant messages', s.ims) # instant messages [slackbot] <- no other dms
print(s.conversations) # ["channel1", "channel2" ...]
print(s.groups) # []
```

Seems like the bot token is unable to get user information and any direct messages other than the slackbot itself.

**Comment by sgratzl** [comment]
a bot token has only limited rights. A major limitation of the slack api itself it about direct messages only the creator of a direct message can delete it.

have you tried creating a user token instead?
