### ISSUE TITLE
msg.delete Invalid arguement

### ISSUE THREAD

**Issue by C-Qingpi** [sgratzl/slack_cleaner2#8]
seems like the slack api requires time_stamp as argument. 
use 

`msg.delete(msg.ts)`

solved problem

**Comment by michTmon** [comment]
I forgot to ask this on the other issue, but have you found a good export/backup tool for Slack? I think the code you posted before puts deleted messages into a channel of their own, but how do you backup that?

**Comment by C-Qingpi** [comment]
> I forgot to ask this on the other issue, but have you found a good export/backup tool for Slack? I think the code you posted before puts deleted messages into a channel of their own, but how do you backup that?

So the entire communication with slack is made through slack web API. You can find documentation on that via slack official website (this is also why you had to add ts to delete history because the API requires that as an argument). The author used [slakcer ](https://pypi.org/project/slacker/) as a python interface. I made my script this way because my PI want's to back up chat history into a private channel. Another option would be output a local file, which you can do by appending string. You can find the complete documentation of slacker here

**Comment by C-Qingpi** [comment]
> I forgot to ask this on the other issue, but have you found a good export/backup tool for Slack? I think the code you posted before puts deleted messages into a channel of their own, but how do you backup that?

the time package is also needed because Slack limits web API deletion as a tier 3 operation, means no short bursts of request.

**Comment by sgratzl** [comment]
re archiving:

yes there is no real good way to archive and replay the slack messages in a free tier. What I used to do it export and delete messages and store them in a mongo db. e.g. https://github.com/sgratzl/slack_cleaner2/blob/master/example/archive.py is a simple example code for that. it will create one collection per channel and stores the message before deleting it.

**Comment by sgratzl** [comment]
re issue: you are using this api to delete messages? then I'm a bit confused about the argument. There is only one optional argument which is `as_user`

https://github.com/sgratzl/slack_cleaner2/blob/master/slack_cleaner2/model.py#L342

which is the same as for the slack api: https://api.slack.com/methods/chat.delete -> as_user

**Comment by michTmon** [comment]
> yes there is no real good way to archive and replay the slack messages in a free tier.

I have been trying to convince my social club to use Slack but they require keeping a historical record. Something like a [pretty HTML viewer](https://levels.io/slack-export-to-html/) would really help. Thanks to  @robhawkins' [post](https://gist.github.com/levelsio/122907e95956602e5c09#gistcomment-2969876) I now have [slack-export](https://github.com/zach-snell/slack-export) and [slack-export-viewer](https://github.com/hfaran/slack-export-viewer) to look into. @hfaran updated recently, which is exciting :smile:

**Comment by sgratzl** [comment]
will close this issue for now since it seems to be to set true to `as_user` flag in `msg.delete()`
