### ISSUE TITLE
Bug: Incorrect installation command in Docs

### ISSUE THREAD

**Issue by ajtadeo** [sgratzl/slack_cleaner2#83]
**Summary**
The installation command listed in the docs is different from the command listed in the GitHub README.md. I figured out the correct command was `pip install slack-cleaner2` on my own, but the docs should be updated to fix this discrepancy. 

**Screenshots**
![image](https://user-images.githubusercontent.com/76643809/221306692-1fb15596-b356-49e4-a119-8133f0697dcc.png)

![image](https://user-images.githubusercontent.com/76643809/221306598-4f86e1f3-b87a-4e6d-9d7d-1e0fe2ad2758.png)

**Comment by sgratzl** [comment]
thx
