### ISSUE TITLE
before not working with file removal

### ISSUE THREAD

**Issue by majava3000** [sgratzl/slack_cleaner2#84]
Was trying to figure out how to remove files before specific date from myself and just couldn't get it to work properly (using the cli).

Narrowed it down to `before` not working. Using `20230101` as the before date, noticed this in the log:
`list all files(user=None, after=None, before=1672524000.0, types=all, channel=XYZZXYZ`

Ie, when using a string input, the time is expanded into a float and that is used as parameter. This parameter will not actually match at all and this resulted in all files being listed (ie, before was ignored completely).

I forced the type to int (modifying code) and that resulted in no files being listed at all.

Additionally for others using the CLI, please note that channels need to be specified, otherwise the main loop will never consider deletion, so this was more or less the command line I used:

`slack-cleaner2 --token XYZZY --rate=1 --file --user USERNAME --before 20230101 --channel '.*' --regex  --log --perform`

- Version: 3.2.0
- Python Version: 3.8 (3.8.10-0ubuntu1~20.04.6), 64-bit

Here's the code that I ended up using to solve my issue:
```
#!/usr/bin/env python3

from slack_cleaner2 import SlackCleaner
import time

s = SlackCleaner('<TOKEN>', sleep_for=1)

cutoff = "20230101"
cutoff = int(time.mktime(time.strptime(cutoff, "%Y%m%d")))

for file in s.files():
    if file.user.name == 'username':
        created = file.json['created']
        if created >= cutoff:
            print(f'File {file} is too fresh, not deleting')
            continue
        print(f'Deleting: {file}: ')
        file.delete()
```

**Comment by sgratzl** [comment]
should be fixed with v3.2.1
