### ISSUE TITLE
cannot delete bot message in ims

### ISSUE THREAD

**Issue by bwmgd** [sgratzl/slack_cleaner2#87]
`cannot delete entry: claude:2023-05-17T14:30:00.311919 (bot):    ̄\_(ツ)_/ ̄: cant_delete_message`

**Screenshots / Sketches**

```python
s = SlackCleaner(TOKEN)
for c in s.ims:
    for msg in c.msgs():
        msg.delete(replies=True, files=True)
```

**Context**

- Version: latest 
- Python Version: 3.11

**Additional context**

My onw message can delete, but the bot message still here.

**Comment by sgratzl** [comment]
I think that is a limitation of the Slack SDK. In IM i can only delete the token owner messages
