### ISSUE TITLE
--rate cli option doesn't seem to do anything

### ISSUE THREAD

**Issue by navels** [sgratzl/slack_cleaner2#91]
The `--rate` cli option doesn't seem to have an effect.  Am running this command:

```
slack-cleaner2 --token <token> --channel <channel> --message --as_user --rate 2 --perform
```

and no matter what I put for the rate it deletes the messages pretty quickly and then gets throttled, sleeps, and keeps going.

**Comment by sgratzl** [comment]
fix in latest reslease
